#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/pyxis

PRODUCT_COPY_FILES += \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/CFR_para.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F3B_src1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F3B_src1.dat \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F3B_src2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F3B_src2.dat \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/body_slim_ui9_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/body_slim_ui9_params.config \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/eyelineblush.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eyelineblush.cng \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/golden_rear_dc_cal_wt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_wt.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/libalfpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/megviifacepp_0_5_2_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/megviifacepp_0_5_2_model \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/camera/visidon_clearshot_params_algoup.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/visidon_clearshot_params_algoup.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/dsi_ss_ea8076_fhd_cmd_display_f3b_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_ss_ea8076_fhd_cmd_display_f3b_mi.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/hdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_config.cfg \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sdr_config.cfg \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/adux1050_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/adux1050_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmi160_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cm3526_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_adux1050_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_adux1050_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_ak991x_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_bmi160_0-spi.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_bmi160_0-spi.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_tcs3701.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_tmd3702_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sdm670_tsl2540_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_tsl2540_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tcs3701.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd3702_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/config/tsl2540_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tsl2540_0.json \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-camera.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-high.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-map.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-nolimits.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-phone.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-pubgmhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-pubgmhd.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-sgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-sgame.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710-tgame.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine-sdm710.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm710.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/pyxis/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx582_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx582_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx586_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx586_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_ov02a10_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_ov02a10_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_s5k4h7_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_s5k4h7_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_ofilm_imx582_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_ofilm_imx582_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_ofilm_ov02a10_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_ofilm_ov02a10_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_ofilm_s5k4h7_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_ofilm_s5k4h7_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_ofilm_s5kgd1_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_ofilm_s5kgd1_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_sunny_s5kgd1_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_sunny_s5kgd1_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_imx582_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_imx582_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_imx586_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_imx586_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_ov02a10_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_ov02a10_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_s5k4h7_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_s5k4h7_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_imx582_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_imx582_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_ov02a10_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_ov02a10_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_s5k4h7_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_s5k4h7_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii_global.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i_global.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/components/etc/morpho_lowlight4.0.xml:$(TARGET_COPY_OUT_VENDOR)/lib/camera/components/etc/morpho_lowlight4.0.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/components/etc/morpho_lowlight4.0_adrc_high.xml:$(TARGET_COPY_OUT_VENDOR)/lib/camera/components/etc/morpho_lowlight4.0_adrc_high.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/components/etc/morpho_lowlight4.0_adrc_high_1.xml:$(TARGET_COPY_OUT_VENDOR)/lib/camera/components/etc/morpho_lowlight4.0_adrc_high_1.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/components/etc/visidon_clearshot_params.xml:$(TARGET_COPY_OUT_VENDOR)/lib/camera/components/etc/visidon_clearshot_params.xml \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/mibokeh_712_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_712_opencl.bin

PRODUCT_PACKAGES += \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libalCFR \
    libalhLDC \
    libarcsoft_beautyshot \
    libarcsoft_bodyslim \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_supernight \
    libmibokeh_712 \
    libmpbase \
    libnanopb \
    libsensorslog \
    libsnsapi \
    libssc \
    com.qti.sensor.pyxis_imx582 \
    com.qti.sensor.pyxis_imx586 \
    com.qti.sensor.pyxis_ov02a10 \
    com.qti.sensor.pyxis_s5k4h7 \
    com.qti.sensor.pyxis_s5kgd1 \
    com.altek.node.depurple \
    com.altek.node.distortioncorrection \
    com.arcsoft.node.bodyslim \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.capturefusion \
    com.arcsoft.node.distortioncorrection \
    com.arcsoft.node.hdr \
    com.arcsoft.node.hdrchecker \
    com.arcsoft.node.realtimebokeh \
    com.arcsoft.node.skinbeautifier \
    com.arcsoft.node.smoothtransition \
    com.arcsoft.node.superlowlight \
    com.mi.node.aiasd \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.mimovie \
    com.qti.node.photosolid \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.node.xiaomigenderage \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.eis \
    com.vidhance.stats.aec_dmbr \
    com.visidon.node.clearshot \
    com.visidon.node.sr \
    com.xiaomi.node.mibokeh \
    com.xiaomi.node.mifragment \
    com.xiaomi.node.misegment \
    camera.qcom \
    com.qti.chi.override \
    libFaceGrade \
    libSNPE \
    libXMFD_AgeGender \
    lib_denoiser3 \
    libalLDC \
    libalRnBRT_GL_GBWRAPPER \
    libarcsoft_dualcam_image_optical_zoom \
    libarcsoft_dualcam_optical_zoom_control \
    libarcsoft_dualcam_video_optical_zoom \
    libc++_shared \
    libcamera_nn_stub \
    libcamera_scene \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxtintlessalgo \
    libcom.qti.chinodeutils \
    libmialgo_fs \
    libmialgo_sd \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libswregistrationalgo \
    libsymphony-cpu \
    libsymphonypower \
    libvideoutils \
    libvidhance \
    android.hardware.gatekeeper@1.0-impl-qti \
    fingerprint.goodix_fod.default \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    libVDDualCameraClearShot \
    libarcsoft_dualcam_refocus_front \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_dualcam_refocus_rear_w \
    libarm_proxy_skel \
    libgf_hal \
    libhvx_proxy_stub \
    libmialgoengine \
    libsensorcal \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsdiaglog \
    libssc_default_listener \
    libssccalapi \
    sensors.ssc \
    sensors.touch \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    libVC1Dec \
    libVC1DecDsp_skel \
    libVDHexagonSuperPhoto_skel \
    libapps_mem_heap \
    libcamera_nn_skel \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_skel \
    libhexagon_nn_skel \
    libproxy_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    misound_karaoke_res \
    misound_karaokemix_res \
    misound_res \
    tas2560_TI_0 \
    android.hardware.gatekeeper@1.0-service-qti \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    init.qcom.sensors \
    sensors.qti
